/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as MylistRouteImport } from './routes/mylist'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as TrendingTypeRouteImport } from './routes/trending.$type'
import { Route as ShowIdRouteImport } from './routes/show.$id'
import { Route as PersonNameRouteImport } from './routes/person.$name'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranscoderRouteImport } from './routes/admin.transcoder'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminRemoteRouteImport } from './routes/admin.remote'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminNetworkRouteImport } from './routes/admin.network'
import { Route as AdminNamingRouteImport } from './routes/admin.naming'
import { Route as AdminLibrariesRouteImport } from './routes/admin.libraries'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminIndexersRouteImport } from './routes/admin.indexers'
import { Route as AdminGeneralRouteImport } from './routes/admin.general'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAcquisitionRouteImport } from './routes/admin.acquisition'
import { Route as DiscoverTypeTmdbIdRouteImport } from './routes/discover.$type.$tmdbId'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MylistRoute = MylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingTypeRoute = TrendingTypeRouteImport.update({
  id: '/trending/$type',
  path: '/trending/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdRoute = ShowIdRouteImport.update({
  id: '/show/$id',
  path: '/show/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonNameRoute = PersonNameRouteImport.update({
  id: '/person/$name',
  path: '/person/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranscoderRoute = AdminTranscoderRouteImport.update({
  id: '/transcoder',
  path: '/transcoder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemoteRoute = AdminRemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNamingRoute = AdminNamingRouteImport.update({
  id: '/naming',
  path: '/naming',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibrariesRoute = AdminLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndexersRoute = AdminIndexersRouteImport.update({
  id: '/indexers',
  path: '/indexers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcquisitionRoute = AdminAcquisitionRouteImport.update({
  id: '/acquisition',
  path: '/acquisition',
  getParentRoute: () => AdminRoute,
} as any)
const DiscoverTypeTmdbIdRoute = DiscoverTypeTmdbIdRouteImport.update({
  id: '/discover/$type/$tmdbId',
  path: '/discover/$type/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/connect': typeof ConnectRoute
  '/films': typeof FilmsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/mylist': typeof MylistRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/indexers': typeof AdminIndexersRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/naming': typeof AdminNamingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/remote': typeof AdminRemoteRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/transcoder': typeof AdminTranscoderRoute
  '/admin/users': typeof AdminUsersRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$name': typeof PersonNameRoute
  '/show/$id': typeof ShowIdRoute
  '/trending/$type': typeof TrendingTypeRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/discover/$type/$tmdbId': typeof DiscoverTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/connect': typeof ConnectRoute
  '/films': typeof FilmsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/mylist': typeof MylistRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/indexers': typeof AdminIndexersRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/naming': typeof AdminNamingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/remote': typeof AdminRemoteRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/transcoder': typeof AdminTranscoderRoute
  '/admin/users': typeof AdminUsersRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$name': typeof PersonNameRoute
  '/show/$id': typeof ShowIdRoute
  '/trending/$type': typeof TrendingTypeRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin': typeof AdminIndexRoute
  '/discover/$type/$tmdbId': typeof DiscoverTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/connect': typeof ConnectRoute
  '/films': typeof FilmsRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/mylist': typeof MylistRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/indexers': typeof AdminIndexersRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/libraries': typeof AdminLibrariesRoute
  '/admin/naming': typeof AdminNamingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/remote': typeof AdminRemoteRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/transcoder': typeof AdminTranscoderRoute
  '/admin/users': typeof AdminUsersRoute
  '/movie/$id': typeof MovieIdRoute
  '/person/$name': typeof PersonNameRoute
  '/show/$id': typeof ShowIdRoute
  '/trending/$type': typeof TrendingTypeRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/discover/$type/$tmdbId': typeof DiscoverTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/connect'
    | '/films'
    | '/invite'
    | '/join'
    | '/mylist'
    | '/requests'
    | '/search'
    | '/series'
    | '/admin/acquisition'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/downloads'
    | '/admin/general'
    | '/admin/indexers'
    | '/admin/jobs'
    | '/admin/libraries'
    | '/admin/naming'
    | '/admin/network'
    | '/admin/pipeline'
    | '/admin/remote'
    | '/admin/requests'
    | '/admin/storage'
    | '/admin/transcoder'
    | '/admin/users'
    | '/movie/$id'
    | '/person/$name'
    | '/show/$id'
    | '/trending/$type'
    | '/watch/$id'
    | '/admin/'
    | '/discover/$type/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/connect'
    | '/films'
    | '/invite'
    | '/join'
    | '/mylist'
    | '/requests'
    | '/search'
    | '/series'
    | '/admin/acquisition'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/downloads'
    | '/admin/general'
    | '/admin/indexers'
    | '/admin/jobs'
    | '/admin/libraries'
    | '/admin/naming'
    | '/admin/network'
    | '/admin/pipeline'
    | '/admin/remote'
    | '/admin/requests'
    | '/admin/storage'
    | '/admin/transcoder'
    | '/admin/users'
    | '/movie/$id'
    | '/person/$name'
    | '/show/$id'
    | '/trending/$type'
    | '/watch/$id'
    | '/admin'
    | '/discover/$type/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/connect'
    | '/films'
    | '/invite'
    | '/join'
    | '/mylist'
    | '/requests'
    | '/search'
    | '/series'
    | '/admin/acquisition'
    | '/admin/ai'
    | '/admin/backup'
    | '/admin/downloads'
    | '/admin/general'
    | '/admin/indexers'
    | '/admin/jobs'
    | '/admin/libraries'
    | '/admin/naming'
    | '/admin/network'
    | '/admin/pipeline'
    | '/admin/remote'
    | '/admin/requests'
    | '/admin/storage'
    | '/admin/transcoder'
    | '/admin/users'
    | '/movie/$id'
    | '/person/$name'
    | '/show/$id'
    | '/trending/$type'
    | '/watch/$id'
    | '/admin/'
    | '/discover/$type/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  FilmsRoute: typeof FilmsRoute
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRoute
  MylistRoute: typeof MylistRoute
  RequestsRoute: typeof RequestsRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  MovieIdRoute: typeof MovieIdRoute
  PersonNameRoute: typeof PersonNameRoute
  ShowIdRoute: typeof ShowIdRoute
  TrendingTypeRoute: typeof TrendingTypeRoute
  WatchIdRoute: typeof WatchIdRoute
  DiscoverTypeTmdbIdRoute: typeof DiscoverTypeTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mylist': {
      id: '/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof MylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending/$type': {
      id: '/trending/$type'
      path: '/trending/$type'
      fullPath: '/trending/$type'
      preLoaderRoute: typeof TrendingTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id': {
      id: '/show/$id'
      path: '/show/$id'
      fullPath: '/show/$id'
      preLoaderRoute: typeof ShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$name': {
      id: '/person/$name'
      path: '/person/$name'
      fullPath: '/person/$name'
      preLoaderRoute: typeof PersonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transcoder': {
      id: '/admin/transcoder'
      path: '/transcoder'
      fullPath: '/admin/transcoder'
      preLoaderRoute: typeof AdminTranscoderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/remote': {
      id: '/admin/remote'
      path: '/remote'
      fullPath: '/admin/remote'
      preLoaderRoute: typeof AdminRemoteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/naming': {
      id: '/admin/naming'
      path: '/naming'
      fullPath: '/admin/naming'
      preLoaderRoute: typeof AdminNamingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/libraries': {
      id: '/admin/libraries'
      path: '/libraries'
      fullPath: '/admin/libraries'
      preLoaderRoute: typeof AdminLibrariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indexers': {
      id: '/admin/indexers'
      path: '/indexers'
      fullPath: '/admin/indexers'
      preLoaderRoute: typeof AdminIndexersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general': {
      id: '/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/acquisition': {
      id: '/admin/acquisition'
      path: '/acquisition'
      fullPath: '/admin/acquisition'
      preLoaderRoute: typeof AdminAcquisitionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/discover/$type/$tmdbId': {
      id: '/discover/$type/$tmdbId'
      path: '/discover/$type/$tmdbId'
      fullPath: '/discover/$type/$tmdbId'
      preLoaderRoute: typeof DiscoverTypeTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcquisitionRoute: typeof AdminAcquisitionRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminIndexersRoute: typeof AdminIndexersRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLibrariesRoute: typeof AdminLibrariesRoute
  AdminNamingRoute: typeof AdminNamingRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRemoteRoute: typeof AdminRemoteRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminTranscoderRoute: typeof AdminTranscoderRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcquisitionRoute: AdminAcquisitionRoute,
  AdminAiRoute: AdminAiRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminIndexersRoute: AdminIndexersRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLibrariesRoute: AdminLibrariesRoute,
  AdminNamingRoute: AdminNamingRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRemoteRoute: AdminRemoteRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminTranscoderRoute: AdminTranscoderRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ConnectRoute: ConnectRoute,
  FilmsRoute: FilmsRoute,
  InviteRoute: InviteRoute,
  JoinRoute: JoinRoute,
  MylistRoute: MylistRoute,
  RequestsRoute: RequestsRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  MovieIdRoute: MovieIdRoute,
  PersonNameRoute: PersonNameRoute,
  ShowIdRoute: ShowIdRoute,
  TrendingTypeRoute: TrendingTypeRoute,
  WatchIdRoute: WatchIdRoute,
  DiscoverTypeTmdbIdRoute: DiscoverTypeTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
