// GENERATED by packages/ui/scripts/gen-icons.ts. Do not edit by hand.
// Source of truth: ./registry.ts. Regenerate with `bun run icons:gen`.

/** One SVG element of a glyph: its tag and its attributes. */
export type IconNode = readonly [tag: string, attrs: Readonly<Record<string, string | number>>];

export interface IconGlyph {
  /** Filled glyphs paint with `fill`; outline glyphs stroke at `strokeWidth`. */
  filled: boolean;
  nodes: readonly IconNode[];
}

export const ICONS = {
  'adjustments-horizontal': {
    filled: false,
    nodes: [
      ['path', { d: 'M12 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0' }],
      ['path', { d: 'M4 6l8 0' }],
      ['path', { d: 'M16 6l4 0' }],
      ['path', { d: 'M6 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0' }],
      ['path', { d: 'M4 12l2 0' }],
      ['path', { d: 'M10 12l10 0' }],
      ['path', { d: 'M15 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0' }],
      ['path', { d: 'M4 18l11 0' }],
      ['path', { d: 'M19 18l1 0' }],
    ],
  },
  backspace: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M20 6a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-11l-5 -5a1.5 1.5 0 0 1 0 -2l5 -5l11 0' },
      ],
      ['path', { d: 'M12 10l4 4m0 -4l-4 4' }],
    ],
  },
  'badge-4k': {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10' },
      ],
      ['path', { d: 'M7 9v2a1 1 0 0 0 1 1h1' }],
      ['path', { d: 'M10 9v6' }],
      ['path', { d: 'M14 9v6' }],
      ['path', { d: 'M17 9l-2 3l2 3' }],
      ['path', { d: 'M15 12h-1' }],
    ],
  },
  'badge-cc': {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10' },
      ],
      ['path', { d: 'M10 10.5a1.5 1.5 0 0 0 -3 0v3a1.5 1.5 0 0 0 3 0' }],
      ['path', { d: 'M17 10.5a1.5 1.5 0 0 0 -3 0v3a1.5 1.5 0 0 0 3 0' }],
    ],
  },
  'chart-bar': {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -6' },
      ],
      [
        'path',
        { d: 'M15 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -10' },
      ],
      [
        'path',
        { d: 'M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -14' },
      ],
      ['path', { d: 'M4 20h14' }],
    ],
  },
  check: { filled: false, nodes: [['path', { d: 'M5 12l5 5l10 -10' }]] },
  'chevron-down': { filled: false, nodes: [['path', { d: 'M6 9l6 6l6 -6' }]] },
  'chevron-left': { filled: false, nodes: [['path', { d: 'M15 6l-6 6l6 6' }]] },
  'chevron-right': { filled: false, nodes: [['path', { d: 'M9 6l6 6l-6 6' }]] },
  'chevron-up': { filled: false, nodes: [['path', { d: 'M6 15l6 -6l6 6' }]] },
  'chevrons-left': {
    filled: false,
    nodes: [
      ['path', { d: 'M11 7l-5 5l5 5' }],
      ['path', { d: 'M17 7l-5 5l5 5' }],
    ],
  },
  'chevrons-right': {
    filled: false,
    nodes: [
      ['path', { d: 'M7 7l5 5l-5 5' }],
      ['path', { d: 'M13 7l5 5l-5 5' }],
    ],
  },
  clock: {
    filled: false,
    nodes: [
      ['path', { d: 'M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0' }],
      ['path', { d: 'M12 7v5l3 3' }],
    ],
  },
  cpu: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M5 6a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -12' },
      ],
      ['path', { d: 'M9 9h6v6h-6l0 -6' }],
      ['path', { d: 'M3 10h2' }],
      ['path', { d: 'M3 14h2' }],
      ['path', { d: 'M10 3v2' }],
      ['path', { d: 'M14 3v2' }],
      ['path', { d: 'M21 10h-2' }],
      ['path', { d: 'M21 14h-2' }],
      ['path', { d: 'M14 21v-2' }],
      ['path', { d: 'M10 21v-2' }],
    ],
  },
  gauge: {
    filled: false,
    nodes: [
      ['path', { d: 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0' }],
      ['path', { d: 'M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0' }],
      ['path', { d: 'M13.41 10.59l2.59 -2.59' }],
      ['path', { d: 'M7 12a5 5 0 0 1 5 -5' }],
    ],
  },
  keyboard: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M2 8a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2l0 -8' },
      ],
      ['path', { d: 'M6 10l0 .01' }],
      ['path', { d: 'M10 10l0 .01' }],
      ['path', { d: 'M14 10l0 .01' }],
      ['path', { d: 'M18 10l0 .01' }],
      ['path', { d: 'M6 14l0 .01' }],
      ['path', { d: 'M18 14l0 .01' }],
      ['path', { d: 'M10 14l4 .01' }],
    ],
  },
  language: {
    filled: false,
    nodes: [
      ['path', { d: 'M9 6.371c0 4.418 -2.239 6.629 -5 6.629' }],
      ['path', { d: 'M4 6.371h7' }],
      ['path', { d: 'M5 9c0 2.144 2.252 3.908 6 4' }],
      ['path', { d: 'M12 20l4 -9l4 9' }],
      ['path', { d: 'M19.1 18h-6.2' }],
      ['path', { d: 'M6.694 3l.793 .582' }],
    ],
  },
  list: {
    filled: false,
    nodes: [
      ['path', { d: 'M9 6l11 0' }],
      ['path', { d: 'M9 12l11 0' }],
      ['path', { d: 'M9 18l11 0' }],
      ['path', { d: 'M5 6l0 .01' }],
      ['path', { d: 'M5 12l0 .01' }],
      ['path', { d: 'M5 18l0 .01' }],
    ],
  },
  lock: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M5 13a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6' },
      ],
      ['path', { d: 'M11 16a1 1 0 1 0 2 0a1 1 0 0 0 -2 0' }],
      ['path', { d: 'M8 11v-4a4 4 0 1 1 8 0v4' }],
    ],
  },
  logout: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2' },
      ],
      ['path', { d: 'M9 12h12l-3 -3' }],
      ['path', { d: 'M18 15l3 -3' }],
    ],
  },
  maximize: {
    filled: false,
    nodes: [
      ['path', { d: 'M4 8v-2a2 2 0 0 1 2 -2h2' }],
      ['path', { d: 'M4 16v2a2 2 0 0 0 2 2h2' }],
      ['path', { d: 'M16 4h2a2 2 0 0 1 2 2v2' }],
      ['path', { d: 'M16 20h2a2 2 0 0 0 2 -2v-2' }],
    ],
  },
  minimize: {
    filled: false,
    nodes: [
      ['path', { d: 'M15 19v-2a2 2 0 0 1 2 -2h2' }],
      ['path', { d: 'M15 5v2a2 2 0 0 0 2 2h2' }],
      ['path', { d: 'M5 15h2a2 2 0 0 1 2 2v2' }],
      ['path', { d: 'M5 9h2a2 2 0 0 0 2 -2v-2' }],
    ],
  },
  movie: {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12' },
      ],
      ['path', { d: 'M8 4l0 16' }],
      ['path', { d: 'M16 4l0 16' }],
      ['path', { d: 'M4 8l4 0' }],
      ['path', { d: 'M4 16l4 0' }],
      ['path', { d: 'M4 12l16 0' }],
      ['path', { d: 'M16 8l4 0' }],
      ['path', { d: 'M16 16l4 0' }],
    ],
  },
  'picture-in-picture': {
    filled: false,
    nodes: [
      ['path', { d: 'M11 19h-6a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v4' }],
      [
        'path',
        { d: 'M14 15a1 1 0 0 1 1 -1h5a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-5a1 1 0 0 1 -1 -1l0 -3' },
      ],
    ],
  },
  'player-pause-filled': {
    filled: true,
    nodes: [
      [
        'path',
        { d: 'M9 4h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h2a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2z' },
      ],
      [
        'path',
        { d: 'M17 4h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h2a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2z' },
      ],
    ],
  },
  'player-play-filled': {
    filled: true,
    nodes: [
      [
        'path',
        {
          d: 'M6 4v16a1 1 0 0 0 1.524 .852l13 -8a1 1 0 0 0 0 -1.704l-13 -8a1 1 0 0 0 -1.524 .852z',
        },
      ],
    ],
  },
  'player-stop-filled': {
    filled: true,
    nodes: [
      [
        'path',
        { d: 'M17 4h-10a3 3 0 0 0 -3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3 -3v-10a3 3 0 0 0 -3 -3z' },
      ],
    ],
  },
  'player-track-next-filled': {
    filled: true,
    nodes: [
      [
        'path',
        {
          d: 'M2 5v14c0 .86 1.012 1.318 1.659 .753l8 -7a1 1 0 0 0 0 -1.506l-8 -7c-.647 -.565 -1.659 -.106 -1.659 .753z',
        },
      ],
      [
        'path',
        {
          d: 'M13 5v14c0 .86 1.012 1.318 1.659 .753l8 -7a1 1 0 0 0 0 -1.506l-8 -7c-.647 -.565 -1.659 -.106 -1.659 .753z',
        },
      ],
    ],
  },
  plus: {
    filled: false,
    nodes: [
      ['path', { d: 'M12 5l0 14' }],
      ['path', { d: 'M5 12l14 0' }],
    ],
  },
  power: {
    filled: false,
    nodes: [
      ['path', { d: 'M7 6a7.75 7.75 0 1 0 10 0' }],
      ['path', { d: 'M12 4l0 8' }],
    ],
  },
  repeat: {
    filled: false,
    nodes: [
      ['path', { d: 'M4 12v-3a3 3 0 0 1 3 -3h13m-3 -3l3 3l-3 3' }],
      ['path', { d: 'M20 12v3a3 3 0 0 1 -3 3h-13m3 3l-3 -3l3 -3' }],
    ],
  },
  'rotate-clockwise-2': {
    filled: false,
    nodes: [
      ['path', { d: 'M9 4.55a8 8 0 0 1 6 14.9m0 -4.45v5h5' }],
      ['path', { d: 'M5.63 7.16l0 .01' }],
      ['path', { d: 'M4.06 11l0 .01' }],
      ['path', { d: 'M4.63 15.1l0 .01' }],
      ['path', { d: 'M7.16 18.37l0 .01' }],
      ['path', { d: 'M11 19.94l0 .01' }],
    ],
  },
  search: {
    filled: false,
    nodes: [
      ['path', { d: 'M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0' }],
      ['path', { d: 'M21 21l-6 -6' }],
    ],
  },
  'server-2': {
    filled: false,
    nodes: [
      [
        'path',
        { d: 'M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2' },
      ],
      [
        'path',
        { d: 'M3 15a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -2' },
      ],
      ['path', { d: 'M7 8l0 .01' }],
      ['path', { d: 'M7 16l0 .01' }],
      ['path', { d: 'M11 8h6' }],
      ['path', { d: 'M11 16h6' }],
    ],
  },
  settings: {
    filled: false,
    nodes: [
      [
        'path',
        {
          d: 'M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065',
        },
      ],
      ['path', { d: 'M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0' }],
    ],
  },
  space: { filled: false, nodes: [['path', { d: 'M4 10v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1 -1v-3' }]] },
  sparkles: {
    filled: false,
    nodes: [
      [
        'path',
        {
          d: 'M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6',
        },
      ],
    ],
  },
  trash: {
    filled: false,
    nodes: [
      ['path', { d: 'M4 7l16 0' }],
      ['path', { d: 'M10 11l0 6' }],
      ['path', { d: 'M14 11l0 6' }],
      ['path', { d: 'M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12' }],
      ['path', { d: 'M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3' }],
    ],
  },
  typography: {
    filled: false,
    nodes: [
      ['path', { d: 'M4 20l3 0' }],
      ['path', { d: 'M14 20l7 0' }],
      ['path', { d: 'M6.9 15l6.9 0' }],
      ['path', { d: 'M10.2 6.3l5.8 13.7' }],
      ['path', { d: 'M5 20l6 -16l2 0l7 16' }],
    ],
  },
  'users-group': {
    filled: false,
    nodes: [
      ['path', { d: 'M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0' }],
      ['path', { d: 'M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1' }],
      ['path', { d: 'M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0' }],
      ['path', { d: 'M17 10h2a2 2 0 0 1 2 2v1' }],
      ['path', { d: 'M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0' }],
      ['path', { d: 'M3 13v-1a2 2 0 0 1 2 -2h2' }],
    ],
  },
  volume: {
    filled: false,
    nodes: [
      ['path', { d: 'M15 8a5 5 0 0 1 0 8' }],
      ['path', { d: 'M17.7 5a9 9 0 0 1 0 14' }],
      [
        'path',
        {
          d: 'M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5',
        },
      ],
    ],
  },
  'volume-2': {
    filled: false,
    nodes: [
      ['path', { d: 'M15 8a5 5 0 0 1 0 8' }],
      [
        'path',
        {
          d: 'M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5',
        },
      ],
    ],
  },
  'volume-3': {
    filled: false,
    nodes: [
      [
        'path',
        {
          d: 'M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5',
        },
      ],
      ['path', { d: 'M16 10l4 4m0 -4l-4 4' }],
    ],
  },
  'volume-off': {
    filled: false,
    nodes: [
      ['path', { d: 'M15 8a5 5 0 0 1 1.912 4.934m-1.377 2.602a5 5 0 0 1 -.535 .464' }],
      ['path', { d: 'M17.7 5a9 9 0 0 1 2.362 11.086m-1.676 2.299a9 9 0 0 1 -.686 .615' }],
      [
        'path',
        {
          d: 'M9.069 5.054l.431 -.554a.8 .8 0 0 1 1.5 .5v2m0 4v8a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l1.294 -1.664',
        },
      ],
      ['path', { d: 'M3 3l18 18' }],
    ],
  },
  'wave-sine': {
    filled: false,
    nodes: [
      [
        'path',
        {
          d: 'M21 12h-2c-.894 0 -1.662 -.857 -1.761 -2c-.296 -3.45 -.749 -6 -2.749 -6s-2.5 3.582 -2.5 8s-.5 8 -2.5 8s-2.452 -2.547 -2.749 -6c-.1 -1.147 -.867 -2 -1.763 -2h-2',
        },
      ],
    ],
  },
  'wifi-off': {
    filled: false,
    nodes: [
      ['path', { d: 'M12 18l.01 0' }],
      ['path', { d: 'M9.172 15.172a4 4 0 0 1 5.656 0' }],
      [
        'path',
        { d: 'M6.343 12.343a7.963 7.963 0 0 1 3.864 -2.14m4.163 .155a7.965 7.965 0 0 1 3.287 2' },
      ],
      ['path', { d: 'M3.515 9.515a12 12 0 0 1 3.544 -2.455m3.101 -.92a12 12 0 0 1 10.325 3.374' }],
      ['path', { d: 'M3 3l18 18' }],
    ],
  },
  'world-search': {
    filled: false,
    nodes: [
      ['path', { d: 'M21 12a9 9 0 1 0 -9 9' }],
      ['path', { d: 'M3.6 9h16.8' }],
      ['path', { d: 'M3.6 15h7.9' }],
      ['path', { d: 'M11.5 3a17 17 0 0 0 0 18' }],
      ['path', { d: 'M12.5 3a16.984 16.984 0 0 1 2.574 8.62' }],
      ['path', { d: 'M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0' }],
      ['path', { d: 'M20.2 20.2l1.8 1.8' }],
    ],
  },
  x: {
    filled: false,
    nodes: [
      ['path', { d: 'M18 6l-12 12' }],
      ['path', { d: 'M6 6l12 12' }],
    ],
  },
} as const satisfies Record<string, IconGlyph>;

export type IconName = keyof typeof ICONS;

/** Tabler draws every glyph on a 24x24 grid. */
export const ICON_VIEWBOX = 24;
