// @generated by scripts/gen-modules.ts from modules/hello.module.md - edit that file, then run `bun run modules:gen`.

import type { LumaModule, ModuleComponentProps } from '@luma/module-sdk';
import manifest from '../../module.json';

function HelloPanel({ host }: ModuleComponentProps) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-lg font-semibold text-text">Hello from a single-file module</h2>
      <p className="text-sm text-muted">
        Authored in one file, expanded by the module codegen. Its icon is a real
        icon.svg served from the backend.
      </p>
      <p className="text-xs text-dim">
        module id: {manifest.id} · host locale: {host.i18n.locale}
      </p>
    </section>
  );
}

export const module: LumaModule = {
  id: manifest.id,
  version: manifest.version,
  dependsOn: manifest.dependsOn,
  navItems: [{ to: '/admin/m/hello', label: manifest.name, section: 'admin' }],
  routes: [{ path: 'hello', component: HelloPanel }],
};
