//! @generated by scripts/gen-modules.ts from modules/hello.module.md - edit that file, then run `bun run modules:gen`.

use luma_module_sdk::EmbeddedModule;

/// This module's registry entry (manifest + packaged icon embedded at compile time).
pub const MODULE: EmbeddedModule = EmbeddedModule::new(include_str!("../../module.json"), include_bytes!("../../icon.svg"));
