#!/usr/bin/env bun
// Generates src/primitives/icons/icons.generated.ts from the slugs listed in
// src/primitives/icons/registry.ts, using @tabler/icons' node data.
//
//   bun run icons:gen     (regenerate)
//   bun run icons:check   (regenerate + fail on any diff; runs in CI)
//
// See registry.ts for why the icons are generated rather than imported.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_SLUGS } from '../src/primitives/icons/registry';

const require = createRequire(import.meta.url);

// @tabler/icons' exports map is `"./*": "./icons/*"`, so the node-data JSON at
// the package ROOT is not reachable as a subpath import. Resolve a file that IS
// exported and walk back up to the package directory.
const iconsDir = dirname(dirname(require.resolve('@tabler/icons/outline/check.svg')));
const nodeData = (name: string): NodeMap =>
  JSON.parse(readFileSync(join(dirname(iconsDir), name), 'utf8'));

const outline = nodeData('tabler-nodes-outline.json');
const filled = nodeData('tabler-nodes-filled.json');

/** Tabler ships each icon as a list of [tag, attributes] pairs. */
type IconNode = [string, Record<string, string | number>];
type NodeMap = Record<string, IconNode[]>;

const OUT = fileURLToPath(new URL('../src/primitives/icons/icons.generated.ts', import.meta.url));

/** SVG elements Tabler actually uses. Anything else means the renderers need a
 * new case, so fail loudly rather than silently dropping part of a glyph. */
const SUPPORTED = new Set(['path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse']);

interface Resolved {
  slug: string;
  filled: boolean;
  nodes: IconNode[];
}

const FILLED_SUFFIX = '-filled';

function resolve(slug: string): Resolved {
  // Tabler publishes filled glyphs as "<name>-filled" but keys them in the
  // filled node map under the bare name, so the suffix selects the MAP.
  const isFilled = slug.endsWith(FILLED_SUFFIX);
  const base = isFilled ? slug.slice(0, -FILLED_SUFFIX.length) : slug;
  const nodes = isFilled ? filled[base] : outline[base];
  if (!nodes) throw new Error(`Unknown Tabler icon slug: "${slug}"`);
  for (const [tag] of nodes) {
    if (!SUPPORTED.has(tag)) {
      throw new Error(`Icon "${slug}" uses <${tag}>, which the Icon renderers do not handle yet`);
    }
  }
  return { slug, filled: isFilled, nodes };
}

const icons = ICON_SLUGS.map(resolve);

const body = icons
  .map((i) => `  '${i.slug}': { filled: ${i.filled}, nodes: ${JSON.stringify(i.nodes)} },`)
  .join('\n');

const source = `// GENERATED by packages/ui/scripts/gen-icons.ts. Do not edit by hand.
// Source of truth: ./registry.ts. Regenerate with \`bun run icons:gen\`.

/** One SVG element of a glyph: its tag and its attributes. */
export type IconNode = readonly [tag: string, attrs: Readonly<Record<string, string | number>>];

export interface IconGlyph {
  /** Filled glyphs paint with \`fill\`; outline glyphs stroke at \`strokeWidth\`. */
  filled: boolean;
  nodes: readonly IconNode[];
}

export const ICONS = {
${body}
} as const satisfies Record<string, IconGlyph>;

export type IconName = keyof typeof ICONS;

/** Tabler draws every glyph on a 24x24 grid. */
export const ICON_VIEWBOX = 24;
`;

writeFileSync(OUT, source);
console.log(`wrote icons.generated.ts (${icons.length} icons, ${source.length} bytes)`);
