#!/usr/bin/env bun
// Generates packages/ui/src/styles/tokens/*.css FROM the TypeScript tokens, so
// the design system has exactly ONE source of truth instead of a TS copy and a
// CSS copy drifting apart. The web + desktop clients keep consuming the CSS
// custom properties; the TV app consumes the TS objects directly.
//
//   bun run tokens:gen     (regenerate)
//   bun run tokens:check   (regenerate + fail on any diff; runs in CI)

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { colors } from '../src/tokens/colors';
import { glow, motion, ring, shadow } from '../src/tokens/effects';
import { gutter, radius, rhythm, space } from '../src/tokens/layout';
import { fonts, tracking, typeSpec } from '../src/tokens/typography';

const OUT = fileURLToPath(new URL('../src/styles/tokens/', import.meta.url));
const HEAD = '/* GENERATED by packages/ui/scripts/gen-token-css.ts. Do not edit by hand. */\n';

const block = (lines: string[]) => `${HEAD}:root {\n${lines.join('\n')}\n}\n`;
const bezier = (b: readonly number[]) => `cubic-bezier(${b.join(', ')})`;
/** A section heading inside the :root block, blank-line separated. */
const section = (title: string) => ['', `  /* ${title} */`];

/** TS token key to its published CSS custom-property name. Explicit rather than
 * derived: `surface1` and `h265` do not kebab-case the same way, and these names
 * are a public contract the web + desktop stylesheets already consume. */
const CSS_COLOR: Record<keyof typeof colors, string> = {
  bg: 'bg',
  surface1: 'surface-1',
  surface2: 'surface-2',
  surface3: 'surface-3',
  overlay: 'overlay',
  border: 'border',
  borderStrong: 'border-strong',
  text: 'text',
  textMuted: 'text-muted',
  textDim: 'text-dim',
  accent: 'accent',
  accentHover: 'accent-hover',
  accentBright: 'accent-bright',
  accentInk: 'accent-ink',
  accentSoft: 'accent-soft',
  success: 'success',
  info: 'info',
  hdr: 'hdr',
  h265: 'h265',
  danger: 'danger',
};

const color = (k: keyof typeof colors, note = '') =>
  `  --kroma-${CSS_COLOR[k]}: ${colors[k].toLowerCase()};${note && ` /* ${note} */`}`;

function colorsCss(): string {
  return block([
    '  /* Surfaces: deep cinematic charcoal */',
    ...(
      ['bg', 'surface1', 'surface2', 'surface3', 'overlay', 'border', 'borderStrong'] as const
    ).map((k) => color(k)),
    ...section('Text on dark'),
    ...(['text', 'textMuted', 'textDim'] as const).map((k) => color(k)),
    ...section('Brand accent: warm amber'),
    ...(['accent', 'accentHover', 'accentBright', 'accentInk', 'accentSoft'] as const).map((k) =>
      color(k),
    ),
    ...section('Semantic + quality badges'),
    color('success', 'Disponible / Vu'),
    color('info', 'Recherche / reseau'),
    color('hdr', 'badge HDR'),
    color('h265', 'badge H.265'),
    color('danger'),
    ...section('Semantic aliases'),
    '  --surface-page: var(--kroma-bg);',
    '  --surface-card: var(--kroma-surface-1);',
    '  --surface-raised: var(--kroma-surface-2);',
    '  --text-body: var(--kroma-text);',
    '  --text-secondary: var(--kroma-text-muted);',
    '  --text-tertiary: var(--kroma-text-dim);',
    '  --brand: var(--kroma-accent);',
    '  --brand-ink: var(--kroma-accent-ink);',
  ]);
}

function spacingCss(): string {
  return block([
    ...Object.entries(space).map(([k, v]) => `  --space-${k}: ${v}px;`),
    ...section('Layout gutters'),
    `  --gutter-web: ${gutter.web}px; /* desktop page side padding */`,
    `  --gutter-tv: ${gutter.tv}px; /* 10-foot side padding */`,
    `  --gutter-mobile: ${gutter.mobile}px;`,
    ...section('Component rhythm'),
    `  --row-gap: ${rhythm.rowGap}px; /* carousel card gap (web) */`,
    `  --card-w: ${rhythm.cardWidth}px; /* default poster width (web) */`,
  ]);
}

const RADIUS_NOTE: Partial<Record<keyof typeof radius, string>> = {
  md: 'buttons',
  lg: 'posters / cards',
  xl: 'large cards, rails',
  '2xl': 'panels, modals',
};

function effectsCss(): string {
  // Rings reference var(--kroma-accent) rather than the literal hex the TS token
  // carries, so a themed override of the accent still retints them in CSS land.
  const accentVar = (s: string) => s.replace(colors.accent, 'var(--kroma-accent)');
  return block([
    '  /* Corner radii */',
    ...Object.entries(radius).map(([k, v]) => {
      const note = RADIUS_NOTE[k as keyof typeof radius];
      return `  --radius-${k}: ${v}px;${note ? ` /* ${note} */` : ''}`;
    }),
    ...section('Elevation'),
    ...Object.entries(shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
    ...section('Focus + glow (10-foot / TV)'),
    `  --ring-focus: ${accentVar(ring.focus)};`,
    `  --ring-focus-sm: ${accentVar(ring.focusSm)};`,
    ...Object.entries(glow).map(([k, v]) => `  --glow-${k}: ${v};`),
    ...section('Motion'),
    `  --ease-out: ${bezier(motion.bezier.out)};`,
    `  --ease-spring: ${bezier(motion.bezier.spring)};`,
    ...Object.entries(motion.duration).map(([k, v]) => `  --dur-${k}: ${v / 1000}s;`),
    `  --press-scale: ${motion.pressScale}; /* buttons shrink on :active */`,
    `  --hover-lift: ${motion.focusLift}px; /* cards translateY on hover */`,
  ]);
}

function typographyCss(): string {
  const role = (s: (typeof typeSpec)[keyof typeof typeSpec]) =>
    `${s.weight} ${s.size}px / ${s.ratio} var(--font-${s.family})`;
  return block([
    '  /* Families: display grotesk for titles, humanist grotesk for UI */',
    `  --font-display: "${fonts.display}", system-ui, sans-serif;`,
    `  --font-ui: "${fonts.ui}", system-ui, sans-serif;`,
    ...section('Roles (font shorthand: weight size/line family)'),
    ...Object.entries(typeSpec).map(([k, v]) => `  --type-${k}: ${role(v)};`),
    ...section('Overline modifier: letter-spacing .12em; text-transform:uppercase'),
    `  --tracking-overline: ${tracking.overline}em;`,
    `  --tracking-display: ${tracking.display}em;`,
  ]);
}

const files: Record<string, string> = {
  'colors.css': colorsCss(),
  'spacing.css': spacingCss(),
  'effects.css': effectsCss(),
  'typography.css': typographyCss(),
};

for (const [name, body] of Object.entries(files)) {
  writeFileSync(OUT + name, body);
  console.log(`wrote ${name} (${body.split('\n').length - 1} lines)`);
}
