//! Portable backup: dump the *non-reproducible* identity + config state
//! (accounts, settings, acquisition indexers / download clients, watch history,
//! resume positions, invites, cron overrides) to a JSON document and restore it
//! on another server.
//!
//! The catalogue itself is **not** exported it's regenerated by a re-scan on
//! the target, which reproduces *identical* item IDs because the library
//! definitions (and their stable IDs) travel inside the `settings` rows. See
//! `crate::services::scan::ids` for the id derivation.
//!
//! Restore runs on a connection with `foreign_keys = OFF` so `progress` rows
//! insert even before the catalogue exists; rows whose item isn't present yet
//! sit inert and reconnect once the admin points the library at its media and
//! re-scans (same `lib_id` ⇒ same item id). Order-independent, no data loss.

use std::collections::BTreeMap;

use anyhow::{Context, Result};
use rusqlite::types::{Value as SqlValue, ValueRef};
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use super::{now_or_blank, Pool};

/// On-disk shape version; bump on an incompatible change.
const VERSION: u32 = 1;

/// Tables carried by a portable backup. Everything else (catalogue, embeddings,
/// AI sections, sessions, job run history, and the machine-specific `downloads`
/// torrent state) is regenerated and left out. `settings` carries the VPN /
/// naming / acquisition preferences; `indexers` and `download_clients` are the
/// admin's acquisition config (their credentials ride inside the
/// password-encrypted archive); `requests` + `wanted` carry the users' media
/// wishlist and its episode ledger. `progress`/`watched`/`my_list` are item-keyed
/// user state that re-links by `item_id` once a re-scan recreates the catalogue
/// with matching ids.
const TABLES: &[&str] = &[
    "users",
    "settings",
    "indexers",
    "download_clients",
    "requests",
    "wanted",
    "invites",
    "play_history",
    "job_schedules",
    "progress",
    "watched",
    "my_list",
];

/// A portable backup: one row-set per exported table, plus metadata. Serde-only
/// (the clients treat the file as an opaque blob), so no ts-rs wire type.
#[derive(Debug, Serialize, Deserialize)]
pub struct BackupDoc {
    pub version: u32,
    pub exported_at: String,
    /// table name → rows, each row a `{column: value}` object.
    pub tables: BTreeMap<String, Vec<Map<String, Value>>>,
    /// User-uploaded files the rows reference but that live outside the DB
    /// (custom avatars in the image cache): cache filename → hex of the bytes.
    /// Populated by `services::backup`, not the DB layer. `default` so older
    /// (pre-assets) backups still deserialize.
    #[serde(default)]
    pub assets: BTreeMap<String, String>,
}

/// Dump every portable table to a [`BackupDoc`]. Tables owned by a module
/// (`indexers` / `download_clients`) only exist once that module's migrations
/// have run, so a table that is absent (module never installed / disabled before
/// its schema was created) is skipped rather than erroring.
pub fn export_portable(pool: &Pool) -> Result<BackupDoc> {
    let conn = pool.get()?;
    let mut tables = BTreeMap::new();
    for &t in TABLES {
        if !table_exists(&conn, t)? {
            continue;
        }
        tables.insert(t.to_string(), dump_query(&conn, &format!("SELECT * FROM {t}"))?);
    }
    Ok(BackupDoc { version: VERSION, exported_at: now_or_blank(), tables, assets: BTreeMap::new() })
}

/// Whether `name` is a table in the current database (module-owned tables may not
/// be, see [`export_portable`]).
fn table_exists(conn: &Connection, name: &str) -> Result<bool> {
    let n: i64 = conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?1",
        [name],
        |r| r.get(0),
    )?;
    Ok(n > 0)
}

/// Restore a [`BackupDoc`] into the database, replacing rows by primary key.
/// Runs in one transaction with foreign keys disabled (see module docs). When
/// `reset` is set, the portable tables are emptied first (a true A→B clone)
/// still inside the same transaction, so a crash mid-restore rolls back wholesale.
/// Returns `(table, rows_written)` pairs in restore order.
pub fn import_portable(pool: &Pool, doc: &BackupDoc, reset: bool) -> Result<Vec<(String, usize)>> {
    if doc.version > VERSION {
        anyhow::bail!("backup version {} is newer than supported {VERSION}", doc.version);
    }
    let mut conn = pool.get()?;
    // Insert across the catalogue gap: `progress.item_id` references rows that a
    // fresh target doesn't have yet. Orphans are inert and reconnect on re-scan.
    // The pragma must toggle *outside* a transaction; restore it before the
    // connection returns to the pool (pooled conns reapply PRAGMAS only on open).
    conn.execute_batch("PRAGMA foreign_keys = OFF;")?;
    let result = restore_all(&mut conn, doc, reset);
    let _ = conn.execute_batch("PRAGMA foreign_keys = ON;");
    result
}

/// The transactional body of [`import_portable`], split out so the caller can
/// restore `foreign_keys` whether it succeeds or fails.
fn restore_all(conn: &mut rusqlite::Connection, doc: &BackupDoc, reset: bool) -> Result<Vec<(String, usize)>> {
    let tx = conn.transaction()?;
    if reset {
        for &t in TABLES {
            if table_exists(&tx, t)? {
                tx.execute(&format!("DELETE FROM {t}"), [])?;
            }
        }
    }
    let mut summary = Vec::new();
    for &t in TABLES {
        if let Some(rows) = doc.tables.get(t) {
            // Skip a table the target lacks (a module present in the source but
            // absent here); its config simply isn't restored.
            if !table_exists(&tx, t)? {
                continue;
            }
            let n = restore_rows(&tx, t, rows).with_context(|| format!("restoring {t}"))?;
            summary.push((t.to_string(), n));
        }
    }
    tx.commit()?;
    Ok(summary)
}

// ----- generic row passthrough ------------------------------------------------

/// Run `sql` and map every row to a `{column: value}` JSON object.
fn dump_query(conn: &Connection, sql: &str) -> Result<Vec<Map<String, Value>>> {
    let mut stmt = conn.prepare(sql)?;
    let cols: Vec<String> = stmt.column_names().into_iter().map(String::from).collect();
    let mut rows = stmt.query([])?;
    let mut out = Vec::new();
    while let Some(row) = rows.next()? {
        let mut obj = Map::new();
        for (i, col) in cols.iter().enumerate() {
            obj.insert(col.clone(), sql_to_json(row.get_ref(i)?));
        }
        out.push(obj);
    }
    Ok(out)
}

/// `INSERT OR REPLACE` each row into `table` (replace-by-primary-key). Column
/// names are validated as plain identifiers before interpolation.
fn restore_rows(conn: &Connection, table: &str, rows: &[Map<String, Value>]) -> Result<usize> {
    let mut written = 0;
    for row in rows {
        let cols: Vec<&String> = row.keys().filter(|c| is_ident(c)).collect();
        if cols.is_empty() {
            continue;
        }
        let col_list = cols.iter().map(|c| format!("\"{c}\"")).collect::<Vec<_>>().join(",");
        let placeholders = (1..=cols.len()).map(|i| format!("?{i}")).collect::<Vec<_>>().join(",");
        let sql = format!("INSERT OR REPLACE INTO \"{table}\" ({col_list}) VALUES ({placeholders})");
        let values: Vec<SqlValue> = cols.iter().map(|c| json_to_sql(&row[*c])).collect();
        conn.execute(&sql, rusqlite::params_from_iter(values.iter()))?;
        written += 1;
    }
    Ok(written)
}

/// SQLite value → JSON. Blobs become a byte array (none of the exported tables
/// have blob columns today, but keep it lossless).
fn sql_to_json(v: ValueRef<'_>) -> Value {
    match v {
        ValueRef::Null => Value::Null,
        ValueRef::Integer(i) => Value::from(i),
        ValueRef::Real(f) => Value::from(f),
        ValueRef::Text(t) => Value::from(String::from_utf8_lossy(t).into_owned()),
        ValueRef::Blob(b) => Value::from(b.to_vec()),
    }
}

/// JSON → SQLite value, inverse of [`sql_to_json`]. Stored-JSON text columns
/// (`settings.value`, `permissions`, …) round-trip as `Text`.
fn json_to_sql(v: &Value) -> SqlValue {
    match v {
        Value::Null => SqlValue::Null,
        Value::Bool(b) => SqlValue::Integer(*b as i64),
        Value::Number(n) => n
            .as_i64()
            .map(SqlValue::Integer)
            .unwrap_or_else(|| SqlValue::Real(n.as_f64().unwrap_or(0.0))),
        Value::String(s) => SqlValue::Text(s.clone()),
        Value::Array(a) => SqlValue::Blob(a.iter().filter_map(|x| x.as_u64().map(|n| n as u8)).collect()),
        Value::Object(_) => SqlValue::Text(v.to_string()),
    }
}

/// A safe SQL identifier (`[A-Za-z0-9_]+`) guards interpolated column names.
fn is_ident(s: &str) -> bool {
    !s.is_empty() && s.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static SEQ: AtomicU32 = AtomicU32::new(0);

    fn fresh_pool(tag: &str) -> Pool {
        let n = SEQ.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!("luma-bkp-{tag}-{}-{n}.db", std::process::id()));
        let _ = std::fs::remove_file(&path);
        let pool = crate::init(&path).unwrap();
        // The acquisition module tables (`indexers` / `download_clients`) are owned
        // by the module crates now and created by their `ServerModule::migrations`
        // at boot, not by `init`. Backup still dumps them by name (see `TABLES`),
        // so recreate the minimal shape here to exercise that path.
        pool.get()
            .unwrap()
            .execute_batch(
                "CREATE TABLE IF NOT EXISTS indexers (\
                    id TEXT PRIMARY KEY, name TEXT NOT NULL, url TEXT NOT NULL, \
                    api_key TEXT NOT NULL DEFAULT '', categories TEXT NOT NULL DEFAULT '2000,5000', \
                    enabled INTEGER NOT NULL DEFAULT 1, priority INTEGER NOT NULL DEFAULT 0, \
                    kind TEXT NOT NULL DEFAULT 'torznab', definition_id TEXT, \
                    settings TEXT NOT NULL DEFAULT '{}', last_ok_at INTEGER, last_error TEXT, \
                    created_at INTEGER NOT NULL);\
                 CREATE TABLE IF NOT EXISTS download_clients (\
                    id TEXT PRIMARY KEY, kind TEXT NOT NULL, name TEXT NOT NULL, \
                    url TEXT NOT NULL DEFAULT '', username TEXT NOT NULL DEFAULT '', \
                    password TEXT NOT NULL DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1, \
                    priority INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);",
            )
            .unwrap();
        pool
    }

    fn count(pool: &Pool, table: &str) -> i64 {
        pool.get()
            .unwrap()
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |r| r.get(0))
            .unwrap()
    }

    #[test]
    fn roundtrip_restores_state_and_keeps_orphan_progress() {
        let src = fresh_pool("src");
        {
            let c = src.get().unwrap();
            c.execute("INSERT INTO libraries (id,name,kind,path,added_at) VALUES ('lib','L','movie','/x','t')", []).unwrap();
            c.execute("INSERT INTO items (id,kind,title,container,library,added_at) VALUES ('it1','movie','Film','mkv','lib','t')", []).unwrap();
            c.execute("INSERT INTO users (id,email,username,password_hash,created_at) VALUES ('u1','a@b.c','Al','ph','t')", []).unwrap();
            c.execute("INSERT INTO settings (key,value,updated_at) VALUES ('serverName','\"My LUMA\"','t')", []).unwrap();
            c.execute("INSERT INTO progress (user_id,item_id,position_ms,duration_ms,updated_at) VALUES ('u1','it1',1000,5000,'t')", []).unwrap();
            c.execute("INSERT INTO play_history (id,kind,title,started_at,ended_at) VALUES ('h1','movie','Film',1,2)", []).unwrap();
            c.execute("INSERT INTO watched (user_id,item_id,watched_at) VALUES ('u1','it1','t')", []).unwrap();
            c.execute("INSERT INTO my_list (user_id,item_id,added_at) VALUES ('u1','it1','t')", []).unwrap();
            // Acquisition config: an indexer (with its api key) + a download client.
            c.execute("INSERT INTO indexers (id,name,url,api_key,created_at) VALUES ('ix1','Jackett','http://jackett','secret',1)", []).unwrap();
            c.execute("INSERT INTO download_clients (id,kind,name,password,created_at) VALUES ('dc1','qbittorrent','qBit','pw',1)", []).unwrap();
            // A user's media request (wishlist) + its episode ledger.
            c.execute("INSERT INTO requests (id,kind,tmdb_id,title,status,created_at,updated_at) VALUES ('rq1','movie',603,'The Matrix','approved',1,1)", []).unwrap();
            c.execute("INSERT INTO wanted (id,request_id,kind,tmdb_id,title,status,updated_at) VALUES ('wt1','rq1','movie',603,'The Matrix','wanted',1)", []).unwrap();
        }

        let doc = export_portable(&src).unwrap();
        assert_eq!(doc.tables["users"].len(), 1);
        assert_eq!(doc.tables["progress"].len(), 1);
        assert_eq!(doc.tables["watched"].len(), 1);
        assert_eq!(doc.tables["my_list"].len(), 1);
        assert_eq!(doc.tables["indexers"].len(), 1);
        assert_eq!(doc.tables["download_clients"].len(), 1);
        assert_eq!(doc.tables["requests"].len(), 1);
        assert_eq!(doc.tables["wanted"].len(), 1);
        // The catalogue is NOT exported only the portable identity tables.
        assert!(!doc.tables.contains_key("items"));

        // Fresh target with no catalogue (items table empty).
        let dst = fresh_pool("dst");
        import_portable(&dst, &doc, false).unwrap();

        assert_eq!(count(&dst, "users"), 1);
        assert_eq!(count(&dst, "play_history"), 1);
        // The orphan progress row survives the missing item (FK off on import) and
        // will reconnect once a re-scan recreates `it1` with the same id.
        assert_eq!(count(&dst, "items"), 0);
        assert_eq!(count(&dst, "progress"), 1);
        assert_eq!(count(&dst, "watched"), 1);
        assert_eq!(count(&dst, "my_list"), 1);
        // Acquisition config restores, credentials intact (they ride inside the
        // password-encrypted archive at the service layer).
        assert_eq!(count(&dst, "indexers"), 1);
        assert_eq!(count(&dst, "download_clients"), 1);
        assert_eq!(count(&dst, "requests"), 1);
        assert_eq!(count(&dst, "wanted"), 1);
        let api_key: String = dst
            .get()
            .unwrap()
            .query_row("SELECT api_key FROM indexers WHERE id='ix1'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(api_key, "secret");

        let server_name: String = dst
            .get()
            .unwrap()
            .query_row("SELECT value FROM settings WHERE key='serverName'", [], |r| r.get(0))
            .unwrap();
        assert_eq!(server_name, "\"My LUMA\"");

        // foreign_keys must be back ON for the next user of any pooled connection.
        let fk: i64 = dst.get().unwrap().query_row("PRAGMA foreign_keys", [], |r| r.get(0)).unwrap();
        assert_eq!(fk, 1);
    }
}
