// @generated by scripts/gen-modules.ts from modules/*.module.md - edit that file, then run `bun run modules:gen`.

import type { KromaModule } from '@kroma/module-sdk';


/** Every single-file (codegen) module, for the host registry to register. */
export const generatedModules: KromaModule[] = [];
