// @generated by scripts/gen-modules.ts from modules/*.module.md - edit that file, then run `bun run modules:gen`.

import type { LumaModule } from '@luma/module-sdk';
import { module as m_dev_luma_hello } from '@luma/module-dev-luma-hello';

/** Every single-file (codegen) module, for the host registry to register. */
export const generatedModules: LumaModule[] = [m_dev_luma_hello];
