//! @generated by scripts/gen-modules.ts - do not edit.
//!
//! The compile-time module roster: registers every module's manifest and
//! collects the backend behavior (`ServerModule`) of the ones that ship one.
//! Sources: modules/roster.yaml (first-party crates) + modules/*.module.md
//! (single-file codegen modules). No other crate hand-names the module set.
use luma_engine::state::SharedState;
use luma_module_host::ServerModule;
use luma_module_manifest::Registry;

/// Register every module's manifest (+ packaged icon) into the host registry.
pub fn register_all(reg: &mut Registry) {
    reg.register(Box::new(luma_scene::MODULE));
    reg.register(Box::new(luma_whisper::MODULE));
    reg.register(Box::new(luma_vector::MODULE));
    reg.register(Box::new(luma_remote::MODULE));
}

/// The backend behavior of each module that ships one. Concrete over the app's
/// `SharedState`, since the modules' `server_module()` constructors are
/// specialized to it (the roster is the composition layer, so this is fine).
pub fn server_modules() -> Vec<Box<dyn ServerModule<SharedState>>> {
    vec![
        luma_remote::server_module(),
    ]
}
