//! @generated by scripts/gen-modules.ts - do not edit.
//!
//! Registers every single-file (codegen) module into the server registry.
use luma_module_sdk::Registry;

pub fn register_all(reg: &mut Registry) {
    reg.register(Box::new(luma_module_dev_luma_hello::MODULE));
}
