#!/usr/bin/env bun
// Single-file module codegen.
//
// A module can be authored as ONE file, `modules/<name>.module.md`, with:
//   - YAML frontmatter: the manifest (id, name, version, description,
//     dependsOn, provides, permissions, config).
//   - ```svg  : the packaged icon, written to `icon.svg` next to module.json.
//   - ```tsx  : the frontend (required), written to ui/src/index.tsx.
//   - ```rust : OPTIONAL extra backend items (the MODULE const is generated).
//   - ```sql  : OPTIONAL migrations, written to server/migrations.sql.
//   - ```locale.en / ```locale.fr : OPTIONAL message catalogs -> locales/*.json.
//
// It expands each into `server/modules/<id>/{module.json, icon.svg, server/*, ui/*, locales/*}`
// (picked up by the `modules/*/server` cargo member glob and `server/modules/*/ui`
// bun workspace glob), and maintains two aggregator rosters so modules register
// with zero manual wiring: crate `luma-modules-generated` (register_all) and
// package `@luma/modules-generated` (generatedModules).
//
// The `id` MUST be reverse-DNS (e.g. "dev.luma.notes"); it is the runtime join
// key and is sanitized into the crate / package names. Generated files carry an
// @generated header - edit the .module.md, then re-run `bun run modules:gen`.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fenced, frontmatter, REVERSE_DNS, slug } from './module-format';

const ROOT = join(import.meta.dir, '..');
const SRC_DIR = join(ROOT, 'modules');
const OUT_ROOT = join(ROOT, 'server', 'modules');
const BE_ROSTER = join(ROOT, 'server', 'crates', 'luma-modules-generated');
const FE_ROSTER = join(ROOT, 'packages', 'modules-generated');

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/** The generated `MODULE` const: an `EmbeddedModule` built from the packaged
 *  `module.json` (+ `icon.svg`), which owns the whole `Module` impl. Any author
 *  `rust` block is appended after it. */
function genModule(hasIcon: boolean): string {
  const ctor = hasIcon
    ? 'EmbeddedModule::new(include_str!("../../module.json"), include_bytes!("../../icon.svg"))'
    : 'EmbeddedModule::iconless(include_str!("../../module.json"))';
  return `use luma_module_sdk::EmbeddedModule;

/// This module's registry entry (manifest + packaged icon embedded at compile time).
pub const MODULE: EmbeddedModule = ${ctor};`;
}

const rustHeader = (file: string) =>
  `//! @generated by scripts/gen-modules.ts from modules/${file} - edit that file, then run \`bun run modules:gen\`.\n`;
const tsHeader = (file: string) =>
  `// @generated by scripts/gen-modules.ts from modules/${file} - edit that file, then run \`bun run modules:gen\`.\n`;

const files = readdirSync(SRC_DIR).filter((f) => f.endsWith('.module.md'));

interface Gen {
  id: string;
  crate: string;
  crateIdent: string;
  pkg: string;
  aliasIdent: string;
}
const generated: Gen[] = [];

for (const file of files) {
  const md = readFileSync(join(SRC_DIR, file), 'utf8');
  const fm = frontmatter(md);
  if (!fm) throw new Error(`${file}: missing YAML frontmatter (--- ... ---)`);
  const manifest = fm as { id: string; version: string };
  const id = manifest.id;
  if (!REVERSE_DNS.test(id)) {
    throw new Error(`${file}: id "${id}" must be reverse-DNS (e.g. dev.luma.notes)`);
  }
  const tsx = fenced(md, 'tsx');
  if (!tsx) throw new Error(`${file}: missing a \`\`\`tsx block`);
  const svg = fenced(md, 'svg');
  const rustExtra = fenced(md, 'rust');
  const sql = fenced(md, 'sql');

  const name = `module-${slug(id)}`;
  const crate = `luma-${name}`;
  const pkg = `@luma/${name}`;
  const dir = join(OUT_ROOT, id);
  generated.push({
    id,
    crate,
    crateIdent: crate.replace(/-/g, '_'),
    pkg,
    aliasIdent: `m_${slug(id).replace(/-/g, '_')}`,
  });

  // Packaged icon file, sitting next to module.json.
  if (svg) write(join(dir, 'icon.svg'), `${svg.trim()}\n`);
  // Manifest (no inline icon).
  write(join(dir, 'module.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  // Optional message catalogs (the ui imports these into the module's `locales`).
  for (const code of ['en', 'fr']) {
    const block = fenced(md, `locale.${code}`);
    if (block) write(join(dir, 'locales', `${code}.json`), `${block.trim()}\n`);
  }
  // A short README pointing back at the single-file source.
  write(
    join(dir, 'README.md'),
    `# ${(manifest as { name?: string }).name ?? id}\n\n@generated from \`modules/${file}\`. Edit that file, then run \`bun run modules:gen\`. See \`modules/README.md\` for the module authoring guide.\n`,
  );

  // Backend crate: the generated Plugin, plus any author-provided extra items.
  write(
    join(dir, 'server', 'Cargo.toml'),
    `# @generated by scripts/gen-modules.ts from modules/${file}
[package]
name = "${crate}"
version = "${manifest.version}"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
luma-module-sdk = { workspace = true }
serde_json = { workspace = true }
`,
  );
  let lib = `${rustHeader(file)}\n${genModule(!!svg)}\n`;
  if (rustExtra) lib += `\n${rustExtra.trim()}\n`;
  write(join(dir, 'server', 'src', 'lib.rs'), lib);
  if (sql) {
    write(join(dir, 'server', 'migrations.sql'), `-- @generated from modules/${file}\n${sql.trim()}\n`);
  }

  // Frontend package.
  write(
    join(dir, 'ui', 'package.json'),
    `${JSON.stringify(
      {
        name: pkg,
        version: manifest.version,
        type: 'module',
        exports: { '.': './src/index.tsx' },
        scripts: { typecheck: 'tsgo --noEmit', build: 'tsgo --noEmit' },
        dependencies: { '@luma/module-sdk': 'workspace:*' },
        peerDependencies: { react: '>=18' },
        devDependencies: { '@types/react': '^19', typescript: '^5.6.3' },
      },
      null,
      2,
    )}\n`,
  );
  write(
    join(dir, 'ui', 'tsconfig.json'),
    `${JSON.stringify(
      { extends: '../../../../tsconfig.base.json', compilerOptions: { noEmit: true, types: ['react'] }, include: ['src'] },
      null,
      2,
    )}\n`,
  );
  write(join(dir, 'ui', 'src', 'index.tsx'), `${tsHeader(file)}\n${tsx.trim()}\n`);

  console.log(`module ${id}  ->  ${crate} + ${pkg}${svg ? ' + icon.svg' : ''}`);
}

// ---- BE aggregator: luma-modules-generated ---------------------------------
write(
  join(BE_ROSTER, 'Cargo.toml'),
  `# @generated by scripts/gen-modules.ts - do not edit.
[package]
name = "luma-modules-generated"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
luma-module-sdk = { workspace = true }
${generated.map((g) => `${g.crate} = { path = "../../modules/${g.id}/server" }`).join('\n')}
`,
);
write(
  join(BE_ROSTER, 'src', 'lib.rs'),
  `//! @generated by scripts/gen-modules.ts - do not edit.
//!
//! Registers every single-file (codegen) module into the server registry.
use luma_module_sdk::Registry;

pub fn register_all(reg: &mut Registry) {
${generated.map((g) => `    reg.register(Box::new(${g.crateIdent}::MODULE));`).join('\n')}
}
`,
);

// ---- FE aggregator: @luma/modules-generated --------------------------------
write(
  join(FE_ROSTER, 'package.json'),
  `${JSON.stringify(
    {
      name: '@luma/modules-generated',
      version: '0.0.0',
      type: 'module',
      exports: { '.': './src/index.ts' },
      scripts: { typecheck: 'tsgo --noEmit', build: 'tsgo --noEmit' },
      dependencies: Object.fromEntries([
        ['@luma/module-sdk', 'workspace:*'],
        ...generated.map((g) => [g.pkg, 'workspace:*'] as const),
      ]),
      peerDependencies: { react: '>=18' },
      devDependencies: { '@types/react': '^19', typescript: '^5.6.3' },
    },
    null,
    2,
  )}\n`,
);
write(join(FE_ROSTER, 'tsconfig.json'), `${JSON.stringify({ extends: '../../tsconfig.base.json', compilerOptions: { noEmit: true, types: ['react'] }, include: ['src'] }, null, 2)}\n`);
write(
  join(FE_ROSTER, 'src', 'index.ts'),
  `${tsHeader('*.module.md')}
import type { LumaModule } from '@luma/module-sdk';
${generated.map((g) => `import { module as ${g.aliasIdent} } from '${g.pkg}';`).join('\n')}

/** Every single-file (codegen) module, for the host registry to register. */
export const generatedModules: LumaModule[] = [${generated.map((g) => g.aliasIdent).join(', ')}];
`,
);

console.log(`rosters: ${generated.length} module(s) -> luma-modules-generated + @luma/modules-generated`);
