#!/usr/bin/env bun
// Single-file module codegen.
//
// A module can be authored as ONE file, `modules/<name>.module.md`, with:
//   - YAML frontmatter: the manifest (id, name, version, description,
//     dependsOn, provides, permissions, config).
//   - ```svg  : the packaged icon, written to `icon.svg` next to module.json.
//   - ```tsx  : the frontend (required), written to ui/src/index.tsx.
//   - ```rust : OPTIONAL extra backend items (the MODULE const is generated).
//   - ```sql  : OPTIONAL migrations, written to server/migrations.sql.
//   - ```locale.en / ```locale.fr : OPTIONAL message catalogs -> locales/*.json.
//
// It expands each into `server/modules/<id>/{module.json, icon.svg, server/*, ui/*, locales/*}`
// (picked up by the `modules/*/server` cargo member glob and `server/modules/*/ui`
// bun workspace glob), and maintains two aggregator rosters so modules register
// with zero manual wiring: crate `luma-modules-generated` (register_all) and
// package `@luma/modules-generated` (generatedModules).
//
// The `id` MUST be reverse-DNS (e.g. "dev.luma.notes"); it is the runtime join
// key and is sanitized into the crate / package names. Generated files carry an
// @generated header - edit the .module.md, then re-run `bun run modules:gen`.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fenced, frontmatter, REVERSE_DNS, slug } from './module-format';

const ROOT = join(import.meta.dir, '..');
const SRC_DIR = join(ROOT, 'modules');
const OUT_ROOT = join(ROOT, 'server', 'modules');
const BE_ROSTER = join(ROOT, 'server', 'crates', 'luma-modules-generated');
const FE_ROSTER = join(ROOT, 'packages', 'modules-generated');

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/** The generated `MODULE` const: `embedded_module!()` discovers the packaged
 *  `module.json` (+ `icon.<ext>`, or none) at compile time, so this is one line
 *  regardless of whether the module ships an icon. Any author `rust` block is
 *  appended after it. */
function genModule(): string {
  return `use luma_module_sdk::EmbeddedModule;

/// This module's registry entry (manifest + packaged icon embedded at compile time).
pub const MODULE: EmbeddedModule = luma_module_sdk::embedded_module!();`;
}

const rustHeader = (file: string) =>
  `//! @generated by scripts/gen-modules.ts from modules/${file} - edit that file, then run \`bun run modules:gen\`.\n`;
const tsHeader = (file: string) =>
  `// @generated by scripts/gen-modules.ts from modules/${file} - edit that file, then run \`bun run modules:gen\`.\n`;

// Sorted so the generated roster order is stable across machines / filesystems
// (readdir order is otherwise OS-dependent, producing spurious diffs).
const files = readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.module.md'))
  .sort();

interface Gen {
  id: string;
  crate: string;
  crateIdent: string;
  pkg: string;
  aliasIdent: string;
}
const generated: Gen[] = [];
// Guards against two sources resolving to the same runtime id or the same crate
// name (e.g. `dev.luma.a-b` and `dev.luma.a.b` both slug to `a-b`), which would
// otherwise fail deep in cargo/tsgo with a duplicate-dependency error.
const seenIds = new Set<string>();
const seenCrates = new Set<string>();

for (const file of files) {
  const md = readFileSync(join(SRC_DIR, file), 'utf8');
  const fm = frontmatter(md);
  if (!fm) throw new Error(`${file}: missing YAML frontmatter (--- ... ---)`);
  const manifest = fm as { id: string; version: string };
  const id = manifest.id;
  if (!REVERSE_DNS.test(id)) {
    throw new Error(`${file}: id "${id}" must be reverse-DNS (e.g. dev.luma.notes)`);
  }
  if (typeof manifest.version !== 'string' || !/^\d+\.\d+\.\d+/.test(manifest.version)) {
    throw new Error(
      `${file}: version ${JSON.stringify(manifest.version)} must be semver (e.g. 0.1.0)`,
    );
  }
  const tsx = fenced(md, 'tsx');
  if (!tsx) throw new Error(`${file}: missing a \`\`\`tsx block`);
  const svg = fenced(md, 'svg');
  const rustExtra = fenced(md, 'rust');
  const sql = fenced(md, 'sql');

  const name = `module-${slug(id)}`;
  const crate = `luma-${name}`;
  const pkg = `@luma/${name}`;
  if (seenIds.has(id)) throw new Error(`${file}: duplicate module id "${id}"`);
  if (seenCrates.has(crate)) {
    throw new Error(
      `${file}: id "${id}" derives crate "${crate}", which collides with another module`,
    );
  }
  seenIds.add(id);
  seenCrates.add(crate);
  const dir = join(OUT_ROOT, id);
  generated.push({
    id,
    crate,
    crateIdent: crate.replace(/-/g, '_'),
    pkg,
    aliasIdent: `m_${slug(id).replace(/-/g, '_')}`,
  });

  // Packaged icon file, sitting next to module.json.
  if (svg) write(join(dir, 'icon.svg'), `${svg.trim()}\n`);
  // Manifest (no inline icon).
  write(join(dir, 'module.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  // Optional message catalogs (the ui imports these into the module's `locales`).
  for (const code of ['en', 'fr']) {
    const block = fenced(md, `locale.${code}`);
    if (block) write(join(dir, 'locales', `${code}.json`), `${block.trim()}\n`);
  }
  // A short README pointing back at the single-file source.
  write(
    join(dir, 'README.md'),
    `# ${(manifest as { name?: string }).name ?? id}\n\n@generated from \`modules/${file}\`. Edit that file, then run \`bun run modules:gen\`. See \`modules/README.md\` for the module authoring guide.\n`,
  );

  // Backend crate: the generated Plugin, plus any author-provided extra items.
  write(
    join(dir, 'server', 'Cargo.toml'),
    `# @generated by scripts/gen-modules.ts from modules/${file}
[package]
name = "${crate}"
version = "${manifest.version}"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
luma-module-sdk = { workspace = true }
serde_json = { workspace = true }
`,
  );
  let lib = `${rustHeader(file)}\n${genModule()}\n`;
  if (rustExtra) lib += `\n${rustExtra.trim()}\n`;
  write(join(dir, 'server', 'src', 'lib.rs'), lib);
  if (sql) {
    write(
      join(dir, 'server', 'migrations.sql'),
      `-- @generated from modules/${file}\n${sql.trim()}\n`,
    );
  }

  // Frontend package.
  write(
    join(dir, 'ui', 'package.json'),
    `${JSON.stringify(
      {
        name: pkg,
        version: manifest.version,
        type: 'module',
        exports: { '.': './src/index.tsx' },
        scripts: { typecheck: 'tsgo --noEmit', build: 'tsgo --noEmit' },
        dependencies: { '@luma/module-sdk': 'workspace:*' },
        peerDependencies: { react: '>=18' },
        devDependencies: { '@types/react': '^19', typescript: '^5.6.3' },
      },
      null,
      2,
    )}\n`,
  );
  write(
    join(dir, 'ui', 'tsconfig.json'),
    `${JSON.stringify(
      {
        extends: '../../../../tsconfig.base.json',
        compilerOptions: { noEmit: true, types: ['react'] },
        include: ['src'],
      },
      null,
      2,
    )}\n`,
  );
  write(join(dir, 'ui', 'src', 'index.tsx'), `${tsHeader(file)}\n${tsx.trim()}\n`);

  console.log(`module ${id}  ->  ${crate} + ${pkg}${svg ? ' + icon.svg' : ''}`);
}

// ---- The first-party roster (modules/roster.yaml) --------------------------
// Hand-authored crates under server/modules/<id>/server. Unlike the single-file
// modules above they are NOT generated, only enumerated here so the aggregator
// wires them in without any Rust crate (kernel or binary) hand-naming the set.
interface RosterEntry {
  id: string;
  crate?: string;
  serverModule?: boolean;
  manifestOnly?: boolean;
  icon?: boolean;
}
const rosterDoc = Bun.YAML.parse(readFileSync(join(SRC_DIR, 'roster.yaml'), 'utf8')) as {
  modules?: RosterEntry[];
};
const roster = rosterDoc.modules ?? [];
for (const r of roster) {
  if (!REVERSE_DNS.test(r.id)) throw new Error(`roster.yaml: id "${r.id}" must be reverse-DNS`);
  if (!r.crate && !r.manifestOnly) {
    throw new Error(`roster.yaml: "${r.id}" needs either a \`crate\` or \`manifestOnly: true\``);
  }
  // Cross-check against the single-file (codegen) modules collected above.
  if (seenIds.has(r.id))
    throw new Error(`roster.yaml: id "${r.id}" is also a single-file .module.md`);
  seenIds.add(r.id);
  if (r.crate) {
    if (seenCrates.has(r.crate))
      throw new Error(`roster.yaml: crate "${r.crate}" collides with another module`);
    seenCrates.add(r.crate);
  }
}
const ident = (crate: string) => crate.replace(/-/g, '_');

// ---- BE aggregator: luma-modules-generated ---------------------------------
// Path deps for every crate the roster wires in: the single-file codegen crates
// plus the first-party roster crates (manifest-only modules have no crate).
const crateDeps = [
  ...roster.filter((r) => r.crate).map((r) => ({ crate: r.crate as string, id: r.id })),
  ...generated.map((g) => ({ crate: g.crate, id: g.id })),
];
// Manifest registrations: a MODULE const per crate module, or an inline
// EmbeddedModule (from the packaged module.json + optional icon) for the
// crate-less manifest-only ones. Roster first, then the codegen modules.
const manifestRegs = [
  ...roster.map((r) =>
    r.manifestOnly
      ? `    reg.register(Box::new(luma_module_manifest::EmbeddedModule::${
          r.icon
            ? `new(include_str!("../../../modules/${r.id}/module.json"), include_bytes!("../../../modules/${r.id}/icon.svg"))`
            : `iconless(include_str!("../../../modules/${r.id}/module.json"))`
        }));`
      : `    reg.register(Box::new(${ident(r.crate as string)}::MODULE));`,
  ),
  ...generated.map((g) => `    reg.register(Box::new(${g.crateIdent}::MODULE));`),
];
// Backend behaviors: only the roster crates that export server_module().
const serverModRegs = roster
  .filter((r) => r.serverModule)
  .map((r) => `        ${ident(r.crate as string)}::server_module(),`);

write(
  join(BE_ROSTER, 'Cargo.toml'),
  `# @generated by scripts/gen-modules.ts - do not edit.
[package]
name = "luma-modules-generated"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
luma-module-manifest = { workspace = true }
luma-module-host = { workspace = true }
# For the concrete SharedState the modules' server_module() constructors return.
luma-engine = { workspace = true }
${crateDeps.map((d) => `${d.crate} = { path = "../../modules/${d.id}/server" }`).join('\n')}
`,
);
write(
  join(BE_ROSTER, 'src', 'lib.rs'),
  `//! @generated by scripts/gen-modules.ts - do not edit.
//!
//! The compile-time module roster: registers every module's manifest and
//! collects the backend behavior (\`ServerModule\`) of the ones that ship one.
//! Sources: modules/roster.yaml (first-party crates) + modules/*.module.md
//! (single-file codegen modules). No other crate hand-names the module set.
use luma_engine::state::SharedState;
use luma_module_host::ServerModule;
use luma_module_manifest::Registry;

/// Register every module's manifest (+ packaged icon) into the host registry.
pub fn register_all(${manifestRegs.length === 0 ? '_reg' : 'reg'}: &mut Registry) {
${manifestRegs.join('\n')}
}

/// The backend behavior of each module that ships one. Concrete over the app's
/// \`SharedState\`, since the modules' \`server_module()\` constructors are
/// specialized to it (the roster is the composition layer, so this is fine).
pub fn server_modules() -> Vec<Box<dyn ServerModule<SharedState>>> {
    vec![
${serverModRegs.join('\n')}
    ]
}
`,
);

// ---- FE aggregator: @luma/modules-generated --------------------------------
write(
  join(FE_ROSTER, 'package.json'),
  `${JSON.stringify(
    {
      name: '@luma/modules-generated',
      version: '0.0.0',
      type: 'module',
      exports: { '.': './src/index.ts' },
      scripts: { typecheck: 'tsgo --noEmit', build: 'tsgo --noEmit' },
      dependencies: Object.fromEntries([
        ['@luma/module-sdk', 'workspace:*'],
        ...generated.map((g) => [g.pkg, 'workspace:*'] as const),
      ]),
      peerDependencies: { react: '>=18' },
      devDependencies: { '@types/react': '^19', typescript: '^5.6.3' },
    },
    null,
    2,
  )}\n`,
);
write(
  join(FE_ROSTER, 'tsconfig.json'),
  `${JSON.stringify({ extends: '../../tsconfig.base.json', compilerOptions: { noEmit: true, types: ['react'] }, include: ['src'] }, null, 2)}\n`,
);
write(
  join(FE_ROSTER, 'src', 'index.ts'),
  `${tsHeader('*.module.md')}
import type { LumaModule } from '@luma/module-sdk';
${generated.map((g) => `import { module as ${g.aliasIdent} } from '${g.pkg}';`).join('\n')}

/** Every single-file (codegen) module, for the host registry to register. */
export const generatedModules: LumaModule[] = [${generated.map((g) => g.aliasIdent).join(', ')}];
`,
);

console.log(
  `rosters: ${generated.length} module(s) -> luma-modules-generated + @luma/modules-generated`,
);
